### ISSUE TITLE
Question about the training and testing file

### ISSUE THREAD

**Issue by hurricane2018** [CVLAB-Unibo/Semantic-Mono-Depth#1]
Thank you for your wonderful work. But I have a problem using your code. 
For example, In your "kitti_semantic_stereo_2015_train_split.txt" file.

training/image_2/000012_10.jpg training/image_3/000012_10.jpg /training/semantic/000012_10.png
training/image_2/000065_10.jpg training/image_3/000065_10.jpg /training/semantic/000065_10.png
training/image_2/000165_10.jpg training/image_3/000165_10.jpg /training/semantic/000165_10.png
training/image_2/000107_10.jpg training/image_3/000107_10.jpg /training/semantic/000107_10.png
.......

I download the KITTI semantic dataset, but I only found the image_2 folder, where are the image_3 and semantic folders. The same problem happens in the "kitti_semantic_stereo_2015_test_split.txt:.  Could you provide more details about the training and testing files?  
Thank you very much!

**Comment by Erudia** [comment]
Hello @hurricane2018 ,

I have the same problem and I see you closed the issue. So, did you find the solution ?
Thank you.
