### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by Erudia** [CVLAB-Unibo/Semantic-Mono-Depth#5]
Hello,

I'm interesting in your code but I have a problem with Python libraries. 
I use Python 2.7 and I tried with Tensorflow 2.0 and 1.5.
Tf2 has not contrib library and tf1.5 has not slim and app libraries.
So, have you got any idea please ?

Bests regards

**Comment by mattpoggi** [comment]
Hello @Erudia ,
I tested with tensorflow 1.8 and it works, give it a try.
Bests
